### ISSUE TITLE
[v2] Todo

### ISSUE THREAD

**Issue by DannyvanderJagt** [DannyvanderJagt/DannyvanderJagt#1]
- [x] Improve images of crisp and lightbase
- [x] Add social links
- [x] Test on devices (Iphone, Ipad)
- [x] Spelling check copy
- [ ] ~~Solve vulnerability issues~~ (It's in the sub-packages, disabled the warnings for now)
- [x] Add mail (in footer)
